sample <- read.csv2("household_power_consumption.txt")
elec <- subset(sample, sample$Date %in% c("2/2/2007","1/2/2007"))
elec[,3] <- as.numeric(as.character(elec[,3]))
elec$datetime <- as.POSIXct(paste(elec$Date,elec$Time), format = "%d/%m/%Y %H:%M:%S")
elec[,7] <- as.numeric(as.character(elec[,7]))
elec[,8] <- as.numeric(as.character(elec[,8]))
elec[,9] <- as.numeric(as.character(elec[,9]))
plot(elec$datetime, elec[,7],type="l", xlab="", ylab="Energy sub metering")
lines(elec$datetime,elec[,8], col = "red")
lines(elec$datetime,elec[,9], col = "blue")
legend("topright", lty = c(1,1,1), col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.copy(png, file = "plot3.png")
dev.off()